import { Titillium_Web } from "next/font/google";
import { CircularProgress, NextUIProvider } from "@nextui-org/react";
import ScrollToTopButton from "@/components/ScrollToTopButton/ScrollToTopButton";
import "./globals.css";
import { Suspense } from "react";

const titillium_Web = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

export const metadata = {
  title: process.env.NEXT_APP_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titillium_Web.className}>
        <NextUIProvider>
          <Suspense fallback={<CircularProgress aria-label="Loading..." />}>
            {children}
          </Suspense>
          <ScrollToTopButton />
        </NextUIProvider>
      </body>
    </html>
  );
}
